# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Typomat < Formula
  desc "Turn your code into muscle memory"
  homepage "https://github.com/vupdivup/typomat"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vupdivup/typomat/releases/download/v0.1.0/typomat_0.1.0_darwin_amd64.tar.gz"
      sha256 "5ef6321c3cd0fcd5df05fc29c84ce1e5405a4865aa92118158c2655fb1ab6d5e"

      def install
        bin.install "typomat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vupdivup/typomat/releases/download/v0.1.0/typomat_0.1.0_darwin_arm64.tar.gz"
      sha256 "8d47415ea306387dcc24d87447b1399c1f93e64f1b3ed4124de1e043bb3da5d2"

      def install
        bin.install "typomat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vupdivup/typomat/releases/download/v0.1.0/typomat_0.1.0_linux_amd64.tar.gz"
      sha256 "59479fd2e9d11ff9b944b86ec21ec52f5516c323b5ccbb8e9a206c0602cf1b51"
      def install
        bin.install "typomat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vupdivup/typomat/releases/download/v0.1.0/typomat_0.1.0_linux_arm64.tar.gz"
      sha256 "725557373611f30044a63587b09c7e22e6f64246813981a0e73a00d3c97c461e"
      def install
        bin.install "typomat"
      end
    end
  end
end
