# This file was generated by GoReleaser. DO NOT EDIT.
cask "typomat" do
  name "typomat"
  desc "Turn your code into muscle memory"
  homepage "https://github.com/vupdivup/typomat"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "typomat"

  on_macos do
    on_intel do
      url "https://github.com/vupdivup/typomat/releases/download/v#{version}/typomat_#{version}_darwin_amd64.tar.gz"
      sha256 "330144cd3c58b1f18fd5ac66417211167391aedf6dc1b23ee6dafb0b0dcd3edd"
    end
    on_arm do
      url "https://github.com/vupdivup/typomat/releases/download/v#{version}/typomat_#{version}_darwin_arm64.tar.gz"
      sha256 "aa4604fa5dc3f5a991277169db39f3b2d2099be550f98fe3412260c2759bf871"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vupdivup/typomat/releases/download/v#{version}/typomat_#{version}_linux_amd64.tar.gz"
      sha256 "fde1508c3f6b45da2c63c8a13d408a1deb7138e683a6ad8e8a0972d2af522485"
    end
    on_arm do
      url "https://github.com/vupdivup/typomat/releases/download/v#{version}/typomat_#{version}_linux_arm64.tar.gz"
      sha256 "b66b2c9297c04381b404e1075509e50fba096254949102218a3fd8d475b93c93"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/typomat"]
    end
  end

  # No zap stanza required
end
