# This file was generated by GoReleaser. DO NOT EDIT.
cask "typomat" do
  name "typomat"
  desc "Turn your code into muscle memory"
  homepage "https://github.com/vupdivup/typomat"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "typomat"

  on_macos do
    on_intel do
      url "https://github.com/vupdivup/typomat/releases/download/v#{version}/typomat_#{version}_darwin_amd64.tar.gz"
      sha256 "033f2f89ea6ec61a13722a792732d9e69327de8b96f09264f11831b5621db47d"
    end
    on_arm do
      url "https://github.com/vupdivup/typomat/releases/download/v#{version}/typomat_#{version}_darwin_arm64.tar.gz"
      sha256 "a1a226ad9a970d1593ecf55dee516b0c157ecc0b343a9fbc58588cad2e93685f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vupdivup/typomat/releases/download/v#{version}/typomat_#{version}_linux_amd64.tar.gz"
      sha256 "56588e04f5c19a4930ebdfc383905aa7eabca043f1cee86421801270eb76fccc"
    end
    on_arm do
      url "https://github.com/vupdivup/typomat/releases/download/v#{version}/typomat_#{version}_linux_arm64.tar.gz"
      sha256 "010e100642db154cdf4c287354d667e5eea90ac2741a8ad66d7ea6187f92fe0d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/typomat"]
    end
  end

  # No zap stanza required
end
