# This file was generated by GoReleaser. DO NOT EDIT.
cask "typomat" do
  name "typomat"
  desc "Turn your code into muscle memory"
  homepage "https://github.com/vupdivup/typomat"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "typomat"

  on_macos do
    on_intel do
      url "https://github.com/vupdivup/typomat/releases/download/v#{version}/typomat_#{version}_darwin_amd64.tar.gz"
      sha256 "4bab8ca8715cfef7528d1b7788446f05a70efe8f0d229a97bc7822773ba42f72"
    end
    on_arm do
      url "https://github.com/vupdivup/typomat/releases/download/v#{version}/typomat_#{version}_darwin_arm64.tar.gz"
      sha256 "3bf28d0761c0fc9ddd650be3dbdbfd14f00833a15bf4c1a50959b4fc4e820313"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vupdivup/typomat/releases/download/v#{version}/typomat_#{version}_linux_amd64.tar.gz"
      sha256 "103db00f7f0ba3d2a0e05fb135043e60c4e00430d779207151cba518200d359c"
    end
    on_arm do
      url "https://github.com/vupdivup/typomat/releases/download/v#{version}/typomat_#{version}_linux_arm64.tar.gz"
      sha256 "6e89b8e8bfb4091952f7ab223c08adee93dd13676b6bd15bdbf9ae77041ac5b3"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/typomat"]
    end
  end

  # No zap stanza required
end
